# Generated by Django 3.1.1 on 2020-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20181204_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book of Department (e.g. IT, CSE, etc.)', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='book',
            name='Department',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='management.Department'),
        ),
    ]
