# Generated by Django 3.1.1 on 2020-09-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20200915_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-name',)},
        ),
        migrations.RemoveField(
            model_name='book',
            name='Department',
        ),
        migrations.AddField(
            model_name='book',
            name='department',
            field=models.ManyToManyField(help_text='Select a Department for this book', to='management.Department'),
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
