# Generated by Django 3.1.1 on 2020-09-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20200915_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='book',
            name='department',
        ),
        migrations.AddField(
            model_name='book',
            name='department',
            field=models.CharField(blank=True, help_text='Select a Department for this book', max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=3),
        ),
    ]
