# Generated by Django 3.1.1 on 2020-09-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20200917_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-dname',)},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='dname',
        ),
        migrations.RemoveField(
            model_name='book',
            name='department',
        ),
        migrations.AddField(
            model_name='book',
            name='dname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.department'),
        ),
    ]
