# Generated by Django 3.1.1 on 2020-09-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20200917_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-department',)},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='dname',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dname',
            new_name='department',
        ),
    ]
