# Generated by Django 3.1.1 on 2020-09-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20200917_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reviews',
        ),
    ]
