# Generated by Django 3.1.1 on 2020-09-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_delete_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrower',
            new_name='Issue',
        ),
    ]
